// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbqyqzjtbellkmhmcqck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icXlxemp0YmVsbGttaG1jcWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDcxMTIsImV4cCI6MjA2NjQ4MzExMn0.hgHopNsC_MSLV4y0KimAMeDyYo86eYxhHLPfPFs5nSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);